### Load the Data First

In [1]:
from google.cloud import bigquery
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="sql-bigquery-331719-5129dc99895e.json"

In [2]:
# Create a "Client" object
client = bigquery.Client()

In [5]:
# Construct a reference to the "hacker_news" dataset
dataset_ref = client.dataset("openaq", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

In [6]:
# List all the tables in the "hacker_news" dataset
tables = list(client.list_tables(dataset))

# Print names of all tables in the dataset (there are four!)
for table in tables:  
    print(table.table_id)

global_air_quality

In [7]:
# Construct a reference to the "full" table
table_ref = dataset_ref.table("global_air_quality")

# API request - fetch the table
table = client.get_table(table_ref)

In [8]:
# Print information on all the columns in the "full" table in the "hacker_news" dataset
table.schema

[SchemaField('location', 'STRING', 'NULLABLE', 'Location where data was measured', (), None),
 SchemaField('city', 'STRING', 'NULLABLE', 'City containing location', (), None),
 SchemaField('country', 'STRING', 'NULLABLE', 'Country containing measurement in 2 letter ISO code', (), None),
 SchemaField('pollutant', 'STRING', 'NULLABLE', 'Name of the Pollutant being measured. Allowed values: PM25, PM10, SO2, NO2, O3, CO, BC', (), None),
 SchemaField('value', 'FLOAT', 'NULLABLE', 'Latest measured value for the pollutant', (), None),
 SchemaField('timestamp', 'TIMESTAMP', 'NULLABLE', 'The datetime at which the pollutant was measured, in ISO 8601 format', (), None),
 SchemaField('unit', 'STRING', 'NULLABLE', 'The unit the value was measured in coded by UCUM Code', (), None),
 SchemaField('source_name', 'STRING', 'NULLABLE', 'Name of the source of the data', (), None),
 SchemaField('latitude', 'FLOAT', 'NULLABLE', 'Latitude in decimal degrees. Precision >3 decimal points.', (), None),
 SchemaField('longitude', 'FLOAT', 'NULLABLE', 'Longitude in decimal degrees. Precision >3 decimal points.', (), None),
 SchemaField('averaged_over_in_hours', 'FLOAT', 'NULLABLE', 'The number of hours the value was averaged over.', (), None)]

In [10]:
# Preview the first five lines of the "full" table
client.list_rows(table, max_results=50).to_dataframe()

,location,city,country,pollutant,value,timestamp,unit,source_name,latitude,longitude,averaged_over_in_hours
0,"BTM Layout, Bengaluru - KSPCB",Bengaluru,IN,co,910.00,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.912811,77.609220,0.25
1,"BTM Layout, Bengaluru - KSPCB",Bengaluru,IN,no2,131.87,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.912811,77.609220,0.25
2,"BTM Layout, Bengaluru - KSPCB",Bengaluru,IN,o3,15.57,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.912811,77.609220,0.25
3,"BTM Layout, Bengaluru - KSPCB",Bengaluru,IN,pm25,45.62,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.912811,77.609220,0.25
4,"BTM Layout, Bengaluru - KSPCB",Bengaluru,IN,so2,4.49,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.912811,77.609220,0.25
5,"BWSSB Kadabesanahalli, Bengaluru - KSPCB",Bengaluru,IN,co,840.00,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.938906,77.697270,0.25
6,"BWSSB Kadabesanahalli, Bengaluru - KSPCB",Bengaluru,IN,no2,166.55,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.938906,77.697270,0.25
7,BWSSB Kadabesanahalli,Bengaluru,IN,o3,17.11,2017-02-12 01:45:00+00:00,µg/m³,CPCB,12.938906,77.697270,0.25
8,"BWSSB Kadabesanahalli, Bengaluru - KSPCB",Bengaluru,IN,pm25,40.94,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.938906,77.697270,0.25
9,"BWSSB Kadabesanahalli, Bengaluru - KSPCB",Bengaluru,IN,so2,6.63,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.938906,77.697270,0.25
10,City Railway Station - KSPCB,Bengaluru,IN,co,1510.00,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.977347,77.570694,0.25
11,City Railway Station - KSPCB,Bengaluru,IN,no2,46.86,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.977347,77.570694,0.25
12,City Railway Station - KSPCB,Bengaluru,IN,pm10,218.44,2018-02-22 03:00:00+00:00,µg/m³,CPCB,12.977347,77.570694,0.25
13,City Railway Station - KSPCB,Bengaluru,IN,so2,5.88,2018-02-21 13:30:00+00:00,µg/m³,CPCB,12.977347,77.570694,0.25
14,SaneguravaHalli - KSPCB,Bengaluru,IN,co,330.00,2018-02-21 23:45:00+00:00,µg/m³,CPCB,12.991670,77.545830,0.25
15,SaneguravaHalli - KSPCB,Bengaluru,IN,no2,23.67,2018-02-21 23:45:00+00:00,µg/m³,CPCB,12.991670,77.545830,0.25
16,SaneguravaHalli - KSPCB,Bengaluru,IN,pm10,64.75,2018-02-21 23:45:00+00:00,µg/m³,CPCB,12.991670,77.545830,0.25
17,SaneguravaHalli - KSPCB,Bengaluru,IN,so2,3.88,2018-02-21 23:45:00+00:00,µg/m³,CPCB,12.991670,77.545830,0.25
18,IIT,Chennai,IN,co,850.00,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.992514,80.237450,0.25
19,IIT,Chennai,IN,no2,6.13,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.992514,80.237450,0.25
20,IIT,Chennai,IN,o3,19.79,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.992514,80.237450,0.25
21,IIT,Chennai,IN,pm25,70.00,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.992514,80.237450,0.25
22,IIT,Chennai,IN,so2,7.90,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.992514,80.237450,0.25
23,Alandur Bus Depot,Chennai,IN,co,5300.00,2017-10-11 08:45:00+00:00,µg/m³,CPCB,12.997114,80.191510,0.25
24,Alandur Bus Depot,Chennai,IN,no2,12.39,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.997114,80.191510,0.25
25,Alandur Bus Depot,Chennai,IN,o3,6.82,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.997114,80.191510,0.25
26,Alandur Bus Depot,Chennai,IN,pm25,111.73,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.997114,80.191510,0.25
27,Alandur Bus Depot,Chennai,IN,so2,29.30,2018-02-22 03:45:00+00:00,µg/m³,CPCB,12.997114,80.191510,0.25
28,"Peenya, Bengaluru - KSPCB",Bengaluru,IN,co,970.00,2018-02-22 02:45:00+00:00,µg/m³,CPCB,13.033900,77.513214,0.25
29,"Peenya, Bengaluru - KSPCB",Bengaluru,IN,no2,25.02,2018-02-22 02:45:00+00:00,µg/m³,CPCB,13.033900,77.513214,0.25
30,"Peenya, Bengaluru - KSPCB",Bengaluru,IN,pm25,43.79,2018-02-22 02:45:00+00:00,µg/m³,CPCB,13.033900,77.513214,0.25
31,"Peenya, Bengaluru - KSPCB",Bengaluru,IN,so2,3.83,2018-02-22 02:45:00+00:00,µg/m³,CPCB,13.033900,77.513214,0.25
32,Sanathnagar - Hyderabad - TSPCB,Hyderabad,IN,co,310.00,2017-06-20 06:00:00+00:00,µg/m³,CPCB,17.423298,78.474700,0.25
33,Sanathnagar - Hyderabad - TSPCB,Hyderabad,IN,o3,13.50,2017-06-20 06:00:00+00:00,µg/m³,CPCB,17.423298,78.474700,0.25
34,Sanathnagar - Hyderabad - TSPCB,Hyderabad,IN,pm25,23.00,2017-06-20 06:00:00+00:00,µg/m³,CPCB,17.423298,78.474700,0.25
35,Sanathnagar - Hyderabad - TSPCB,Hyderabad,IN,so2,5.50,2017-06-20 06:00:00+00:00,µg/m³,CPCB,17.423298,78.474700,0.25
36,AAQMS Karve Road Pune,Pune,IN,co,1220.00,2018-02-22 03:00:00+00:00,µg/m³,CPCB,18.497484,73.813490,0.25
37,AAQMS Karve Road Pune,Pune,IN,o3,15.76,2018-02-22 03:00:00+00:00,µg/m³,CPCB,18.497484,73.813490,0.25
38,AAQMS Karve Road Pune,Pune,IN,pm10,165.00,2018-02-22 03:00:00+00:00,µg/m³,CPCB,18.497484,73.813490,0.25
39,AAQMS Karve Road Pune,Pune,IN,pm25,66.00,2018-02-22 03:00:00+00:00,µg/m³,CPCB,18.497484,73.813490,0.25
40,AAQMS Karve Road Pune,Pune,IN,so2,22.85,2018-02-22 03:00:00+00:00,µg/m³,CPCB,18.497484,73.813490,0.25
41,Maharashtra Pollution Control Board Bandra,Mumbai,IN,co,1670.00,2018-02-22 04:00:00+00:00,µg/m³,CPCB,19.041847,72.865520,0.25
42,Maharashtra Pollution Control Board Bandra,Mumbai,IN,no2,7.04,2018-02-22 04:00:00+00:00,µg/m³,CPCB,19.041847,72.865520,0.25
43,Maharashtra Pollution Control Board Bandra,Mumbai,IN,o3,19.21,2018-02-22 04:00:00+00:00,µg/m³,CPCB,19.041847,72.865520,0.25
44,Maharashtra Pollution Control Board Bandra,Mumbai,IN,pm10,295.97,2018-02-22 04:00:00+00:00,µg/m³,CPCB,19.041847,72.865520,0.25
45,Maharashtra Pollution Control Board Bandra,Mumbai,IN,pm25,86.15,2018-02-22 04:00:00+00:00,µg/m³,CPCB,19.041847,72.865520,0.25
46,Maharashtra Pollution Control Board Bandra,Mumbai,IN,so2,18.35,2018-02-22 04:00:00+00:00,µg/m³,CPCB,19.041847,72.865520,0.25
47,Navi Mumbai Municipal Corporation Airoli,Navi Mumbai,IN,pm25,20.40,2017-10-04 04:15:00+00:00,µg/m³,CPCB,19.149400,72.998600,0.25
48,Chandrapur,Chandrapur,IN,co,1020.00,2018-02-22 04:00:00+00:00,µg/m³,CPCB,19.950000,79.300000,0.25
49,Chandrapur,Chandrapur,IN,no2,18.80,2018-02-22 04:00:00+00:00,µg/m³,CPCB,19.950000,79.300000,0.25

### Write SQL Query Now!!!

In [11]:
# Query to select all the items from the "city" column where the "country" column is 'US'
query = """
        SELECT city
        FROM `bigquery-public-data.openaq.global_air_quality`
        WHERE country = 'US'
        """

In [13]:
# Set up the query
query_job = client.query(query)

In [14]:
# API request - run the query, and return a pandas DataFrame
us_cities = query_job.to_dataframe()

In [15]:
# What five cities have the most measurements?
us_cities.city.value_counts().head()

Phoenix-Mesa-Scottsdale                     88
Houston                                     82
Los Angeles-Long Beach-Santa Ana            68
Riverside-San Bernardino-Ontario            60
New York-Northern New Jersey-Long Island    60
Name: city, dtype: int64

In [16]:
query = """
        SELECT city, country
        FROM `bigquery-public-data.openaq.global_air_quality`
        WHERE country = 'US'
        """

In [18]:
# select all columns
query = """
        SELECT *
        FROM `bigquery-public-data.openaq.global_air_quality`
        WHERE country = 'US'
        """

In [20]:
# Query to get the score column from every row where the type column has value "job"
query = """
        SELECT score, title
        FROM `bigquery-public-data.hacker_news.full`
        WHERE type = "job" 
        """

# Create a QueryJobConfig object to estimate size of query without running it
dry_run_config = bigquery.QueryJobConfig(dry_run=True)

# API request - dry run query to estimate costs
dry_run_query_job = client.query(query, job_config=dry_run_config)

print("This query will process {} bytes.".format(dry_run_query_job.total_bytes_processed))

This query will process 494748929 bytes.

In [21]:
# Only run the query if it's less than 1 MB
ONE_MB = 1000*1000
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=ONE_MB)

# Set up the query (will only run if it's less than 1 MB)
safe_query_job = client.query(query, job_config=safe_config)

# API request - try to run the query, and return a pandas DataFrame
safe_query_job.to_dataframe()

InternalServerError: 500 Query exceeded limit for bytes billed: 1000000. 494927872 or higher required.

(job ID: 15064789-0089-47d9-885e-d2fcf13f03cc)

             -----Query Job SQL Follows-----

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:        SELECT score, title
   3:        FROM `bigquery-public-data.hacker_news.full`
   4:        WHERE type = "job"
   5:
    |    .    |    .    |    .    |    .    |    .    |

In [22]:
# Only run the query if it's less than 1 GB
ONE_GB = 1000*1000*1000
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=ONE_GB)

# Set up the query (will only run if it's less than 1 GB)
safe_query_job = client.query(query, job_config=safe_config)

# API request - try to run the query, and return a pandas DataFrame
job_post_scores = safe_query_job.to_dataframe()

# Print average score for job posts
job_post_scores.score.mean()

1.7841263098272444